name: GitHub Actions

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet core 2.2.105
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.105
      - name: Build with dotnet
        run: dotnet build
      - name: Build with dotnet
        run: dotnet test